Update build_and_test.yml

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -15,16 +15,24 @@ jobs:
     - uses: actions/checkout@v2
     - name: Install Dependencies
       run: sudo apt install cmake libboost-filesystem-dev libboost-test-dev gcc
-    - name: Build and Test
+    - name: Print System Information
       run: |
-          export CXX=g++
-          export CC=gcc
-          export CODECOV_TOKEN="c3d08772-6107-422c-886f-ada5c4780d5c"
-          mkdir build && cd build
-          cmake --version
-          g++ --version
-          cat /usr/include/boost/version.hpp
-          cmake .. -DINOTIFY_GCC_COVERAGE=1
-          cmake --build .
-          ctest -VV
-          bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
+        cmake --version
+        g++ --version
+        cat /usr/include/boost/version.hpp
+    - name: Build
+      run: |
+        export CXX=g++
+        export CC=gcc
+        mkdir build && cd build
+        cmake .. -DINOTIFY_GCC_COVERAGE=1
+        cmake --build .
+    - name: Test
+      run: |
+        cd build
+        ctest -VV
+    - name: Generate Coverage Report
+      run: |
+        cd build
+        export CODECOV_TOKEN="c3d08772-6107-422c-886f-ada5c4780d5c"
+        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
